[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
actix-files = "0.6.2"
dotenv = "0.15.0"
env_logger = "0.9.1"
log = "0.4.14"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
shared = { path = "../shared" }
